package com.gbsofts.gbcrypt.main.ui;

import com.gbsofts.gbcrypt.config.SystemConfig;
import com.gbsofts.gbcrypt.util.FileUtil;
import com.gbsofts.gbcrypt.util.UIUtil;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.net.URISyntaxException;
import java.util.Map.Entry;
import java.util.Properties;
import javax.swing.table.DefaultTableModel;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.streetjava.util.SJUtil;

/**
 *
 * @author Luong Dang Dung
 */
public class SystemSettingForm extends javax.swing.JFrame {

    static Logger logger = LogManager.getLogger(SystemSettingForm.class.getName());

    DefaultTableModel model;

    /**
     * Creates new form SystemSetting
     */
    public SystemSettingForm() throws IOException, FileNotFoundException, URISyntaxException {
        initComponents();
        model = (DefaultTableModel) tblConfig.getModel();
        tableRender();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmdSave = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblConfig = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Configuration");

        cmdSave.setText("Save");
        cmdSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSaveActionPerformed(evt);
            }
        });

        tblConfig.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Value"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblConfig);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cmdSave)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 501, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(cmdSave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSaveActionPerformed
        try{

            writeProperties();
            
            UIUtil.POPUP(this, "Save properties successfully!");
        }catch(URISyntaxException | IOException e){
            logger.error(SJUtil.GET_STACKTRACE(e));
        }
    }//GEN-LAST:event_cmdSaveActionPerformed

    private void tableRender() throws FileNotFoundException, IOException, URISyntaxException {
        
            InputStream is = new FileInputStream(FileUtil.getCurdir() + File.separator + SystemConfig.PROPERTIES_FILE);

            Properties props = new Properties();

            props.load(is);

            is.close();

            for (Entry<Object, Object> entry : props.entrySet()) {

                
                String name = entry.getKey().toString();
                String value = entry.getValue().toString();

                Object[] row = {name, value};

                model.addRow(row);
            }
            
            tblConfig.getColumnModel().getColumn(0).setPreferredWidth(200);
            tblConfig.getColumnModel().getColumn(0).setMinWidth(100);
            tblConfig.getColumnModel().getColumn(0).setMaxWidth(400);
        
    }

    private Properties getProperties() {
        int rownum = model.getRowCount();

        Properties props = new Properties();

        for (int i = 0; i < rownum; i++) {
            props.put(model.getValueAt(i, 0).toString(), model.getValueAt(i, 1).toString());
        }

        return props;
    }
    
    private void writeProperties() throws URISyntaxException, FileNotFoundException, IOException{
        OutputStream os = new FileOutputStream(FileUtil.getCurdir() + File.separator + SystemConfig.PROPERTIES_FILE);
        
        String header = "GBCrypt version " + SystemConfig.VERSION;
        
        getProperties().store(os, header);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SystemSettingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SystemSettingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SystemSettingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SystemSettingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new SystemSettingForm().setVisible(true);
                } catch (Exception e) {
                    logger.error(SJUtil.GET_STACKTRACE(e));
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdSave;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblConfig;
    // End of variables declaration//GEN-END:variables
}
